# Generated by Django 6.0.6 on 2026-06-24 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='description',
            new_name='content_en',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='title',
            new_name='title_en',
        ),
        migrations.AddField(
            model_name='news',
            name='content_ta',
            field=models.TextField(default='Tamil News'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='title_ta',
            field=models.CharField(default='Tamil News', max_length=200),
            preserve_default=False,
        ),
    ]
